version: "3.1"
services:
  mysql: 
    image: mysql/mysql-server:5.7
    ports: 
      - 33060:3306
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_ROOT_PASSWORD: secret1
      MYSQL_PASSWORD: secret2 
    volumes:
      - ./projdatabase:/var/lib/db/mysql
    networks:
      - default
    restart: always
    
  springbootapi:
    depends_on:  
      - mysql
    build: ./MeetingAPI
    ports: 
      - 8000:8000
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": 8000,
        "spring.datasource.url" : "jdbc:mysql://mysql:3306/demo?useSSL=false",
        "spring.datasource.username" : "demo",
        "spring.datasource.password" : "secret2",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./MeetingAPI:/var/lib/api
  
  webapp:
    depends_on:
      - springbootapi
    build: ./webApp
    ports:
      - 5500:80
    volumes:
      - ./webApp:/webapp